### ISSUE TITLE
Consider using an Info instead of warning for packages that are not under YunoHost-Apps

### ISSUE THREAD

**Issue by spctrlth** [YunoHost/package_check#116]
When you use the package check tool on an app that's not under YunoHost-Apps, the linter test will give a Warning `! Consider adding your app to the YunoHost-Apps organization to allow the community to contribute more easily`. I think an Info should be enough.

**Comment by yalh76** [comment]
In fact not because is in the [Packing Applications: Good Practise Guidelines](https://yunohost.org/en/packaging_apps_guidelines)
