### ISSUE TITLE
Test a failed upgrade

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost/package_check#12]
As discussed on the forum [here](https://forum.yunohost.org/t/backup-before-upgrade/2668/6), it could prove useful to have  a test case provoke a failed upgrade to test backup-before-upgrade procedure (when existing).
Maybe we can prevent Internet access to make app archive download fail?

**Comment by maniackcrudelis** [comment]
I think the better way to do that is simply to inject an exit 1 in the upgrade script. In the middle of the script.

It's the way I use to test this feature.

**Comment by JimboJoe** [comment]
Why not, but we'll have to make sure we don't add the `exit 1` inside a conditional block.

**Comment by alexAubin** [comment]
Closing because the whole backup-before-upgrade story should be handled by the core, we should not have to test this for every app
