### ISSUE TITLE
Get "https://devbaseimgs.yunohost.org:8443/1.0": remote error: tls: protocol version not supported

### ISSUE THREAD

**Issue by Krakinou** [YunoHost/package_check#120]
Hello,
I have package_checks self hosted on a debian machine.
I get the error `Get "https://devbaseimgs.yunohost.org:8443/1.0": remote error: tls: protocol version not supported` since a few days each time I launch a check.
This does not prevent the test to run thought.

**Comment by yalh76** [comment]
same here.
I think devbaseimgs.yunohost.org lxd should be upgraded .. i's actually using lxd 2.0.11

**Comment by yalh76** [comment]
should be fixed for now after adding TLSv1.3 on the nginx of the host of devbaseimgs
