### ISSUE TITLE
Support new change_url feature

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost/package_check#13]
Since [this PR](https://github.com/YunoHost/yunohost/pull/185) got merged, apps can now provide a `change_url` script to change the URL of an already installed instance.
Package_check should provide tests to cover this feature.

**Comment by maniackcrudelis** [comment]
Hum, one again, github didn't send me a mail...

So, yes, we should add this test.
If you want to try it, we should do that in this file
https://github.com/YunoHost/package_check/blob/master/sub_scripts/testing_process.sh

Simply as a new function with an installation and a call to this script.

**Comment by maniackcrudelis** [comment]
Just to keep an example in sight.
https://github.com/YunoHost/test_apps/blob/master/change_url_app_ynh/scripts/change_url
https://github.com/YunoHost/change_url_app_ynh/blob/master/scripts/change_url

**Comment by maniackcrudelis** [comment]
Done :)
