### ISSUE TITLE
Allow to select tests to be paused via --interrupt

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost/package_check#22]
When developing, the `--interrupt` option is very useful, especially for the 2 first tests `setup_sub_dir` and `setup_root`.
After having these 2 tests passing OK, the `--interrupt` option is still useful for other tests, but it'll imply pausing each time on the 2 firsts tests, which is not always necessary.

The idea would be:
- either to pass tests numbers or identifiers to the `--interrupt` option to select after which test(s) to pause
- or to consider that the 2 first tests:
  - need to be paused when no other test has been selected in the `check_process` file, 
  - don't need to be paused in any other case

**Comment by alexAubin** [comment]
Closing because it's 6 years old and I doubt anybody really does run package check manually and needs this ...
