### ISSUE TITLE
"un truc plus itératif"

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/package_check#24]
(22:28:41) Jean-Baptiste: Sinon, il y a aussi la coquille, qui fait que tu dois tout recommencer sans raison
(22:29:16) Jean-Baptiste: Genre une variable bash non déclarée, qui te fait perdre 10 minutes de chargement
(22:30:15) Jean-Baptiste: J'aimerais bien un truc plus itératif : ça vient de planter, tu veux corriger et on reprend ou alors je supprime tout et je continue ?
(22:31:02) Maniack C: Techniquement ça pourrait s'envisager
(22:31:27) Maniack C: C'est pas très compliqué à faire

**Comment by alexAubin** [comment]
Closing because not clear how that would work ...
