### ISSUE TITLE
Add cache for pip packages

### ISSUE THREAD

**Issue by Jibec** [YunoHost/package_check#25]
Every run of package test is done on a fresh Debian, with many missing packages.

It looks like pip has a default repository for caching purpose, would it be possible to create a folder in the host so package downloads faster?

https://pip.pypa.io/en/stable/reference/pip_install/#caching

**Comment by Jibec** [comment]
Solved by adding this to `/var/lib/lxc/pchecker_lxc/config`

`lxc.mount.entry = /var/cache/pip/cache/ var/cache/pip/cache/ none bind,create=dir 0.0`

and editing snapshot:

```bash
echo -e "\e[1m> Add PIP cache\e[0m"
sudo cp $script_dir/pip.conf /var/lib/lxcsnaps/$LXC_NAME/snap0/rootfs/etc/pip.conf
sudo mkdir -p /var/lib/lxc/$LXC_NAME/rootfs/var/cache/pip/cache/
```

Here is the content of pip.conf:
```
[global]
cache_dir = /var/cache/pip/cache
```

**Comment by alexAubin** [comment]
Closing as wontfix
