### ISSUE TITLE
Add cache for debian packages

### ISSUE THREAD

**Issue by Jibec** [YunoHost/package_check#26]
Every run of package test is done on a fresh Debian, with many missing packages.

Would it be possible to add some kind of proxy so we don't have to download multiple times the same packages?
https://packages.debian.org/jessie/apt-cacher

**Comment by Jibec** [comment]
Solved by adding this to `/var/lib/lxc/pchecker_lxc/config`

> lxc.mount.entry = /var/cache/apt/archives/ var/cache/apt/archives/ none bind,create=dir 0.0

**Comment by alexAubin** [comment]
Closing as wontfix
