### ISSUE TITLE
Crash du script "default_args.py"

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/package_check#3]
Sur certaines questions de manifest, le script `default_args.py` ne parvient pas à parser correctement les questions.

Sur [teamspeak 3](https://github.com/KnooL/ts3_ynh)
```
Traceback (most recent call last):
  File "/root/CI_package_check/auto_build/../package_check/sub_scripts/ci/maniackc.py", line 15, in <module>
    print ":".join(argument_for_question(question, all_choices=True))
  File "/root/CI_package_check/package_check/sub_scripts/ci/default_args.py", line 52, in argument_for_question
    raise Exception("Unknow question type: %s\n" % question_type, question)
Exception: (u'Unknow question type: 64bit or 32bit? (x64 vs x86)\n', {u'ask': {u'en': u'64 bit or 32 bit? (x64 vs x86)'}, u'default': u'64', u'type': u'64bit or 32bit? (x64 vs x86)', u'name': u'System-OS Platform', u'example': u'64'})
```

Sur [mumble server](https://github.com/matlink/mumbleserver_ynh)
```
Traceback (most recent call last):
  File "/root/CI_package_check/auto_build/../package_check/sub_scripts/ci/maniackc.py", line 15, in <module>
    print ":".join(argument_for_question(question, all_choices=True))
  File "/root/CI_package_check/package_check/sub_scripts/ci/default_args.py", line 52, in argument_for_question
    raise Exception("Unknow question type: %s\n" % question_type, question)
Exception: ('Unknow question type: None\n', {u'ask': {u'fr': u'Choisissez un message de bienvenue pour le serveur', u'en': u'Choose a welcome text for your server'}, u'name': u'welcometext', u'example': u'Welcome to my mumble server'})
```

**Comment by Psycojoker** [comment]
Si tu regardes bien c'est parce que:

* pour teamspeak "type" est mis à "64bit or 32bit? (x64 vs x86)" ce qui n'est pas un type valide
* sur mumble : il n'y a tout simplement pas de clef "type" (d'où le `None`)

Donc il faut fixer la manifest de ces applications. Je ferme vu que ce n'est pas un bug de mon côté, si tu penses le contraire hésite pas à réouvrir ;)

**Comment by maniackcrudelis** [comment]
Pas de problème pour moi.
J'ai fixé Package check pour qu'il passe ces apps en erreur.

Au pire un check process évitera le problème

**Comment by Psycojoker** [comment]
Je pense que package_linter ou package_check devrait vérifier ça. Il existe des applications/lib pour vérifier le format d'un fichier json. En avoir un officiel pour YunoHost serait vraiment un + (et un check à faire au moment de l'installation).

**Comment by maniackcrudelis** [comment]
Oui ça me semble une bonne idée de vérifier la syntaxe du json, mais est-ce que ça détecterais l'absence de type?

**Comment by Psycojoker** [comment]
Oui, si on impose que le type soit déclaré dans le format du json.

Exemple d'un outil du genre : http://json-schema.org/

**Comment by maniackcrudelis** [comment]
Il n'y a aucune implémentation en bash...

Mais devrait-on le passer dans le linter pour indiquer une erreur de syntaxe ou dans package check pour indiquer une erreur bloquante?

**Comment by Psycojoker** [comment]
Ca se code facilement en python (je peux faire ça).

Idéalement les 2 je dirais (et dans YunoHost core aussi où on refuserait d'installer une mauvaise app). Le teste est facile à faire, d'autant + si on fait un mini outils en cli appelable de partout.

**Comment by maniackcrudelis** [comment]
Dans le core oui, après si c'est un mini exec, on peut le mettre dans Package check avant de démarrer les tests
