### ISSUE TITLE
Add dependency support

### ISSUE THREAD

**Issue by Jibec** [YunoHost/package_check#31]
When working on agendav, we need either baikal or radicale to be installed.

I'm currently using this hack to let me run my tests, but this will only enable me to test, the official CI will still fail.

diff --git a/sub_scripts/testing_process.sh b/sub_scripts/testing_process.sh
index cea8aac..d318a5a 100644
--- a/sub_scripts/testing_process.sh
+++ b/sub_scripts/testing_process.sh
@@ -32,7 +32,7 @@ SETUP_APP () {
 	current_snapshot=snap0
 
 	# Install the application in a LXC container
-	LXC_START "sudo yunohost --debug app install \"$package_dir\" -a \"$manifest_args_mod\""
+	LXC_START "yunohost app install baikal -a \"domain=$main_domain&path=baikal/&password=ok\" && sudo yunohost --debug app install \"$package_dir\" -a \"$manifest_args_mod\""

Multiple solutions here:

* either enable application installation from an install script
     * it doesn't looks like to work at the moment, bash sends many warnings about running commands from a removed directory: https://stackoverflow.com/questions/12758125/sh-0-getcwd-failed-no-such-file-or-directory-on-cited-drive#21593371 and it fails to find where is the current temporary folder (in my case, it couldn't find anymore ../conf/app.src)
* or enable application installation from manifest
* or enable explicit application dependencies from check_process, which may be a similar need than #28

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost/package_check/tree/pre_install

**Comment by Jibec** [comment]
This worked fine for me, thank you 💟
