### ISSUE TITLE
Les conditions sur des commandes YunoHost CLI retournent des erreurs

### ISSUE THREAD

**Issue by scith** [YunoHost/package_check#4]
Salut,
J'ai l'impression que lorsque l'on teste des commandes YunoHost CLI conditionnellement, leur échec met en échec l'étape package_check

Par exemple le code suivant:
``` bash
	if [[ -n $(sudo yunohost backup info $app-before-upgrade || true) ]]; then
		sudo yunohost backup delete $app-before-upgrade
	fi
```

Met en échec l'upgrade avec comme erreur (Complete.log):
``` txt
2016-12-29 10:00:58,397 INFO     yunohost.hook <lambda> - [2926.1] ++ sudo yunohost backup info rainloop-before-upgrade
2016-12-29 10:00:58,933 INFO     moulinette.actionsmap process - processing action [2944.1]: yunohost.backup.info
2016-12-29 10:00:58,934 WARNING  yunohost.hook <lambda> - [2926.1] L'archive locale de sauvegarde nommée « rainloop-before-upgrade » est inconnue
2016-12-29 10:00:58,933 ERROR    yunohost cli - L'archive locale de sauvegarde nommée « rainloop-before-upgrade » est inconnue
```

En fait la commande yunohost retourne bien "Erreur" si on l'exécute indépendamment. Mais dans une condition ? J'ai pourtant rajouté "|| true" pour l'échapper.

J'ai la même erreur sur un autre package avec la condition `if [ -n $(ynh_app_setting_get transmission rpcpassword || true) ]; then`

J'essaye de bidouiller le code mais sans succès. L'install sans package_check se passe bien

Merci

**Comment by scith** [comment]
En fait je pense que c'est moi qui gère mal le set -e ou trap ... Je vais me documenter

**Comment by maniackcrudelis** [comment]
Probablement oui, car package check ne gère pas l'erreur, il récupère le code de sortie uniquement.

**Comment by scith** [comment]
Bon j'ai toujours ce soucis, c'est étrange. En fait les commandes YunoHost CLI renvoient facilement des erreurs. Mon `sudo yunohost backup info $app-before-upgrade` sans backup renvoie une erreur. Cette erreur n'affecte pas le script ni le trap. Par contre elle stoppe le package_check et le met en erreur.

Tu n'as pas ce soucis sur tes scripts upgrade nextcloud ?

**Comment by maniackcrudelis** [comment]
Si j'ai eu le même problème, même en essayant de rediriger la sortie ou de lui mettre un pipe. Surtout j'avais toujours le message d'erreur.

J'ai utilisé un backup liste avec un grep pour contourner le problème.

À mon avis, le problème avec package check est que l'erreur d'une commande Yunohost doit provoquer une fin de script avec un code d'erreur différents de 0. Comme si le script avait échoué.

**Comment by scith** [comment]
OK bizarre ... Du coup je suis bloqué pour le moment sur couchpotato car je ne connais pas d'alternative pour `if [ -n $(ynh_app_setting_get transmission rpcpassword || true) ]; then`

**Comment by maniackcrudelis** [comment]
Si tu fais un --verbose, à la fin YunoHost te dit qu'il n'y a pas eu d'erreur?

|| true dans le if, ça fausse pas le résultat?
J'avais pas souvenir que ça renvoyais une erreur cette commande, j'aurais eu tendance à le mettre dans une variable et à tester son contenu après. Mais si c'est la commande qui coince, c'est plus gênant.

Hum, chez moi la commande renvoi 0 que la clé existe ou non.

**Comment by maniackcrudelis** [comment]
Je viens de trouver la source de l'erreur, ça bloque le test de [monitorix](https://jenkins-ci-arm.noho.st/jenkins/job/monitorix%20(Community)/1/console) aussi.

Le problème c'est que package check récupère les erreurs dans le log
https://github.com/YunoHost/package_check/blob/master/sub_scripts/log_extractor.sh#L54-L58
Et que même si on redirige la sortie de la commande dans /dev/null, l'erreur est quand même enregistrée dans le log.

Elle aparait pas dans la sortie standard mais quand même dans le log.
Reste à savoir si il faut contourner ça, ou si la redirection dans /dev/null devrait être respectée.

**Comment by maniackcrudelis** [comment]
> Probablement oui, car package check ne gère pas l'erreur, il récupère le code de sortie uniquement.

Donc j'avais tort sur ce point, il vérifie le log pour voir si il y a eu des erreurs durant l'exécution.

Le problème se situe bien sur le log cli qui reçoit l'erreur, quoi qu'il en soit.
Malheureusement, ce log est le seul qui soit suffisamment complet pour analyser la réussite du script. Et on ne peut pas empêcher la commande yunohost d'écrire dans le log.

Donc en attendant mieux, pour ce genre de commande en if, j'ai un écrit un hack innommable...
https://github.com/maniackcrudelis/modele_ynh/blob/master/scripts/.fonctions#L34-L46
