### ISSUE TITLE
stretch support

### ISSUE THREAD

**Issue by Jibec** [YunoHost/package_check#46]
Btw: thanks to aleks who fixed (synchronized) branches stretch/stretch2 on YunoHost, the lxc_build script now runs :)
But it ends up with an unusable container.

See here for the full log: https://paste.fedoraproject.org/paste/UNZ3GR9vUKBzVfsFiaMVjw

Here are a few ideas that may be the cause of this:

# filter

This filter doesn't looks like to be compliant with debian9:
https://github.com/YunoHost/package_check/blob/master/sub_scripts/lxc_check.sh#L266

it does `grep "inet addr"` but it doesn't match the new format of ifconfig.

# interface name

eth0 looks like to be hard-coded in some places:
https://github.com/YunoHost/package_check/search?utf8=%E2%9C%93&q=eth0&type=

I tried to play with some values, none worked...

# ifconfig in Debian 8 and 9

`ifconfig` with Debian 8:
```
eth0      Link encap:Ethernet  HWaddr 52:54:00:2f:7d:bc  
          inet adr:192.168.100.202  Bcast:192.168.100.255  Masque:255.255.255.0
          adr inet6: fe80::5054:ff:fe2f:7dbc/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:97 errors:0 dropped:0 overruns:0 frame:0
          TX packets:71 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:1000 
          RX bytes:9591 (9.3 KiB)  TX bytes:9161 (8.9 KiB)

lo        Link encap:Boucle locale  
          inet adr:127.0.0.1  Masque:255.0.0.0
          adr inet6: ::1/128 Scope:Hôte
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lxc-pchecker Link encap:Ethernet  HWaddr 46:3d:ef:4c:53:9c  
          inet adr:10.1.4.1  Bcast:10.1.4.255  Masque:255.255.255.0
          adr inet6: fe80::443d:efff:fe4c:539c/64 Scope:Lien
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 lg file transmission:0 
          RX bytes:0 (0.0 B)  TX bytes:828 (828.0 B)
```

`ifconfig` with Debian 9:
```
ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.100.211  netmask 255.255.255.0  broadcast 192.168.100.255
        inet6 fe80::5054:ff:fe1a:d368  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:1a:d3:68  txqueuelen 1000  (Ethernet)
        RX packets 93919  bytes 125382140 (119.5 MiB)
        RX errors 0  dropped 4  overruns 0  frame 0
        TX packets 54974  bytes 5099225 (4.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Boucle locale)
        RX packets 6892  bytes 732540 (715.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6892  bytes 732540 (715.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lxc-pchecker: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.1.4.1  netmask 255.255.255.0  broadcast 10.1.4.255
        inet6 fe80::3cef:63ff:fef1:ef5a  prefixlen 64  scopeid 0x20<link>
        ether 3e:ef:63:f1:ef:5a  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 144 (144.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

**Comment by maniackcrudelis** [comment]
Well, ok first, your log (not sure that your have read it...) says:
```
E: Le pilote pour la méthode /usr/lib/apt/methods/https n'a pu être trouvé.
E: Impossible de trouver le paquet yunohost
E: Impossible de trouver le paquet yunohost-admin
```
So... the error seems quite clear.

lxc_check is certainly not updated to work with stretch, since I've just updated lxc_build to make it works for the CI.
There's still work to do to update all package check for stretch, but I didn't have enough time to do it yet.

eth0 is hardcoded INSIDE the container, there's no problem about that because eth0 is defined to be the network interface of the container.

---
Still, there's a real question, should we have the package `apt-transport-https` ? Since this package is usually not installed.
Does YunoHost stretch uses an https entry for the repository ?

**Comment by Jibec** [comment]
indeed, adding apt-transport-https to packets looks like to make it works, thanks.

One thing is for sure: packagers needs to have a package_check that works, we need to be able to test things by ourselves to make the debian 9 migration as smooth as possible.
