### ISSUE TITLE
Docker on package_check

### ISSUE THREAD

**Issue by aymhce** [YunoHost/package_check#49]
Hello, Docker can work on package_check ?

All my apps are failed because Docker don't start on package_check ... But without it, they work (for me and other, example : Collabora on Docker, https://yunohost.org/#/collabora).

That all apps on docker :
- https://github.com/aymhce/collaboradocker_ynh ->https://github.com/YunoHost-Apps/collaboradocker_ynh
- https://github.com/aymhce/diasporadocker_ynh
- https://github.com/YunoHost-Apps/portainer_ynh
- https://github.com/aymhce/yunohost_ynh

Thanks for help (me) :)

**Comment by maniackcrudelis** [comment]
So I guess that isn't really a question.
Docker isn't working into LXC.

So, clearly I'm not using docker, neither that I support it or want to do so.
I don't know why docker isn't working into a LXC container. I think that you should have a look in that direction.
If you can find a way to make docker work in a LXC container, without breaking LXC container for standard usage. I'll merge that into Package check.
