### ISSUE TITLE
Disk full?

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost/package_check#57]
package_check upgrade/backup tests fails with a disk full error (`121701 5072 L’espace disque est insuffisant sur « /home/yunohost.backup/archives »`).
Is there a defined limit on the container storage, or are we only limited by the host / partition space?
Thanks!

**Comment by maniackcrudelis** [comment]
That's it, as you probably understood yourself, there's no limit to the container storage.
If you had this issue, you have to expand the size of your virtual machine.

**Comment by JimboJoe** [comment]
Thanks!
