### ISSUE TITLE
Use two readme for french and english

### ISSUE THREAD

**Issue by M5oul** [YunoHost/package_check#7]
Current readme is too long, and it's hard to understand that there is two languages.
Furthermore it's hard to find where is the separation between two languages.

I suggest to use two files with links between them.
You could see [an example here](https://github.com/reversTeam/Sublivim).

I suggest to put english version as main readme.

**Comment by maniackcrudelis** [comment]
Fix https://github.com/YunoHost/package_check/commit/3db48f2e9bfbf154ef5f845c24961edbe8a80903
