### ISSUE TITLE
Forwarding rules for web access when package_check running in a remote VM/container

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost/package_check#71]
I'm currently running package_check in a remote VM, and usually use the `--interrupt` along with the `ssh -t pchecker_lxc` command to access logs and try some adaptation/fix actions.
Yet, I've never tried/made work a forwarding to connect to the package_check instance through my own browser.
Would there be simple commands / recommendations toward that goal?
Thanks!

**Comment by maniackcrudelis** [comment]
If I understand well, what you're trying to do is to access the web app that is currently tested into packaged check.
As it's only a LXC container, the rules used for iptable should be enough.

So, I guess what's next is to add the correct dns resolution into your hosts.
But you said "remote VM"...
You have nothing more complicated ?

If this remote VM is running YunoHost, it could be done with the app redirect, otherwise I would say that you need a redirection of the domain, so a web server.

Not a package check VM, but that could help you https://crudelis.fr/site/sblog/2020/03/yunohost-inside-yunohost-through-a-vpn/

**Comment by JimboJoe** [comment]
Thanks for your answer, I'll have a look.
My setup sounds complicated but the reasons are simple:
* I have a very modest/old laptop with Linux that can't run efficiently an LXC or VM YunoHost for my tests
* We have a shared Windows desktop that's much more powerful --> I installed VirtualBox and set up a test VM with YunoHost and package_check (and no, I didn't manage to convince every user to switch to Linux yet).

**Comment by maniackcrudelis** [comment]
What's a "shared Windows desktop" ?

**Comment by JimboJoe** [comment]
Well, it's a computer which use is shared across the family :sweat_smile:

**Comment by JimboJoe** [comment]
So, I've read your very detailed and interesting article (thanks for that! :heart_eyes: ), and created the dedicated domains in the YunoHost VM (the distant LXC is a "paused" package_check instance to start with, so I created `domain.tld` and `sous.domain.tld`)
Trying to reach `sous.domain.tld` works as expected, and redirects to `domain.tld` for YunoHost authentication. It fails there with this error message in the nginx log for `domain.tld` on the VM:
```
2020/03/29 17:42:04 [error] 694#694: *4 lua entry thread aborted: runtime error: /usr/share/ssowat/access.lua:77: attempt to concatenate global 'user' (a nil value)
stack traceback:
coroutine 0:
        /usr/share/ssowat/access.lua: in function </usr/share/ssowat/access.lua:1>, client: 10.1.4.1, server: domain.tld, request: "GET /yunohost/sso/?r=aHR0cHM6Ly9zb3VzLmRvbWFpbi50bGQv HTTP/1.1", host: "domain.tld"
```
In your setup, were some applications private or were they all public?

**Comment by maniackcrudelis** [comment]
My installation has only one app, and it's a private one.
I have no issue with the authentication.


I have to admit that I don't understand what that error message means.

**Comment by JimboJoe** [comment]
OK, that's maybe another problem (YunoHost buster alpha?)...
Anyway, that worked a treat with public apps! :+1:

**Comment by maniackcrudelis** [comment]
Indeed, mine isn't a Buster version.

**Comment by alexAubin** [comment]
Closing because sounds like it's fixed / no more feedback
