### ISSUE TITLE
Old mention of official apps

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/package_check#74]
> ! [YEP-1.3] 'non-free' apps can't be officialized.  Their integration is still being discussed, especially for apps with non-free dependencies 

Package check still refers to official apps, while this status does not exist any more.

**Comment by maniackcrudelis** [comment]
Not relative to Official status, but to an integration of non free apps into our lists of apps.
And so far, the answer has always been the same, we refuse non free apps.
