### ISSUE TITLE
Erreur de test d'installation avec des noms de questions terminant par "admin"

### ISSUE THREAD

**Issue by lithrel** [YunoHost/package_check#8]
En mode dégradé, package_check tente de récupérer un utilisateur dans le manifest. Si le `name` d'un des `arguments.install` termine par `admin`, cette ligne https://github.com/YunoHost/package_check/blob/master/package_check.sh#L905 assigne le nom de la question comme `MANIFEST_USER`, qui est ensuite utilisé là https://github.com/YunoHost/package_check/blob/master/sub_scripts/testing_process.sh#L169 pour remplacer sa réponse par `USER_TEST`.
On se retrouve avec ce remplacement :
```
MANIFEST_ARGS=domain=ynh.local&create_admin=Yes&
MANIFEST_ARGS_MOD=domain=sous.ynh.local&create_admin=package_checker&
```
qui fait échouer l'installation si la réponse à `create_admin` devait être comprise dans une liste `["Yes", "No"]` par exemple.

**Comment by maniackcrudelis** [comment]
Simplement je dirais que c'est un "mode dégradé", dont la vocation est juste de pas jeter d'office un package sans check_process.
C'était surtout utile au début de l'utilisation de package check puisque les check_process n'étaient pas répandu.

Aujourd'hui, face un problème de ce genre, la meilleur chose à faire est sans aucun doute d'utiliser un check_process.

**Comment by lithrel** [comment]
ok :)
